[Output]
Format=sysext
Output=katl-endpoint-advertiser
ImageId=katl-endpoint-advertiser
Overlay=yes

[Content]
Bootable=no
BaseTrees=../../_build/mkosi/katl-runtime-root

[Build]
BuildSources=../..
WorkspaceDirectory=/tmp/katl-mkosi-endpoint-advertiser-workspace
