// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: internal/katlc/agentapi/agent.proto

package agentapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KatlcAgent_GetNodeStatus_FullMethodName            = "/katl.agent.v1.KatlcAgent/GetNodeStatus"
	KatlcAgent_SubmitOperation_FullMethodName          = "/katl.agent.v1.KatlcAgent/SubmitOperation"
	KatlcAgent_CreateWorkerJoinMaterial_FullMethodName = "/katl.agent.v1.KatlcAgent/CreateWorkerJoinMaterial"
	KatlcAgent_GetOperation_FullMethodName             = "/katl.agent.v1.KatlcAgent/GetOperation"
	KatlcAgent_WatchOperation_FullMethodName           = "/katl.agent.v1.KatlcAgent/WatchOperation"
)

// KatlcAgentClient is the client API for KatlcAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KatlcAgentClient interface {
	GetNodeStatus(ctx context.Context, in *GetNodeStatusRequest, opts ...grpc.CallOption) (*NodeStatus, error)
	SubmitOperation(ctx context.Context, in *SubmitOperationRequest, opts ...grpc.CallOption) (*OperationAccepted, error)
	CreateWorkerJoinMaterial(ctx context.Context, in *CreateWorkerJoinMaterialRequest, opts ...grpc.CallOption) (*CreateWorkerJoinMaterialResponse, error)
	GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*OperationStatus, error)
	WatchOperation(ctx context.Context, in *WatchOperationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OperationEvent], error)
}

type katlcAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewKatlcAgentClient(cc grpc.ClientConnInterface) KatlcAgentClient {
	return &katlcAgentClient{cc}
}

func (c *katlcAgentClient) GetNodeStatus(ctx context.Context, in *GetNodeStatusRequest, opts ...grpc.CallOption) (*NodeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeStatus)
	err := c.cc.Invoke(ctx, KatlcAgent_GetNodeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *katlcAgentClient) SubmitOperation(ctx context.Context, in *SubmitOperationRequest, opts ...grpc.CallOption) (*OperationAccepted, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationAccepted)
	err := c.cc.Invoke(ctx, KatlcAgent_SubmitOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *katlcAgentClient) CreateWorkerJoinMaterial(ctx context.Context, in *CreateWorkerJoinMaterialRequest, opts ...grpc.CallOption) (*CreateWorkerJoinMaterialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWorkerJoinMaterialResponse)
	err := c.cc.Invoke(ctx, KatlcAgent_CreateWorkerJoinMaterial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *katlcAgentClient) GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*OperationStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationStatus)
	err := c.cc.Invoke(ctx, KatlcAgent_GetOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *katlcAgentClient) WatchOperation(ctx context.Context, in *WatchOperationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OperationEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KatlcAgent_ServiceDesc.Streams[0], KatlcAgent_WatchOperation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchOperationRequest, OperationEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KatlcAgent_WatchOperationClient = grpc.ServerStreamingClient[OperationEvent]

// KatlcAgentServer is the server API for KatlcAgent service.
// All implementations must embed UnimplementedKatlcAgentServer
// for forward compatibility.
type KatlcAgentServer interface {
	GetNodeStatus(context.Context, *GetNodeStatusRequest) (*NodeStatus, error)
	SubmitOperation(context.Context, *SubmitOperationRequest) (*OperationAccepted, error)
	CreateWorkerJoinMaterial(context.Context, *CreateWorkerJoinMaterialRequest) (*CreateWorkerJoinMaterialResponse, error)
	GetOperation(context.Context, *GetOperationRequest) (*OperationStatus, error)
	WatchOperation(*WatchOperationRequest, grpc.ServerStreamingServer[OperationEvent]) error
	mustEmbedUnimplementedKatlcAgentServer()
}

// UnimplementedKatlcAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKatlcAgentServer struct{}

func (UnimplementedKatlcAgentServer) GetNodeStatus(context.Context, *GetNodeStatusRequest) (*NodeStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeStatus not implemented")
}
func (UnimplementedKatlcAgentServer) SubmitOperation(context.Context, *SubmitOperationRequest) (*OperationAccepted, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitOperation not implemented")
}
func (UnimplementedKatlcAgentServer) CreateWorkerJoinMaterial(context.Context, *CreateWorkerJoinMaterialRequest) (*CreateWorkerJoinMaterialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWorkerJoinMaterial not implemented")
}
func (UnimplementedKatlcAgentServer) GetOperation(context.Context, *GetOperationRequest) (*OperationStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOperation not implemented")
}
func (UnimplementedKatlcAgentServer) WatchOperation(*WatchOperationRequest, grpc.ServerStreamingServer[OperationEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchOperation not implemented")
}
func (UnimplementedKatlcAgentServer) mustEmbedUnimplementedKatlcAgentServer() {}
func (UnimplementedKatlcAgentServer) testEmbeddedByValue()                    {}

// UnsafeKatlcAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KatlcAgentServer will
// result in compilation errors.
type UnsafeKatlcAgentServer interface {
	mustEmbedUnimplementedKatlcAgentServer()
}

func RegisterKatlcAgentServer(s grpc.ServiceRegistrar, srv KatlcAgentServer) {
	// If the following call panics, it indicates UnimplementedKatlcAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KatlcAgent_ServiceDesc, srv)
}

func _KatlcAgent_GetNodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KatlcAgentServer).GetNodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KatlcAgent_GetNodeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KatlcAgentServer).GetNodeStatus(ctx, req.(*GetNodeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KatlcAgent_SubmitOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KatlcAgentServer).SubmitOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KatlcAgent_SubmitOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KatlcAgentServer).SubmitOperation(ctx, req.(*SubmitOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KatlcAgent_CreateWorkerJoinMaterial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkerJoinMaterialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KatlcAgentServer).CreateWorkerJoinMaterial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KatlcAgent_CreateWorkerJoinMaterial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KatlcAgentServer).CreateWorkerJoinMaterial(ctx, req.(*CreateWorkerJoinMaterialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KatlcAgent_GetOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KatlcAgentServer).GetOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KatlcAgent_GetOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KatlcAgentServer).GetOperation(ctx, req.(*GetOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KatlcAgent_WatchOperation_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchOperationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KatlcAgentServer).WatchOperation(m, &grpc.GenericServerStream[WatchOperationRequest, OperationEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KatlcAgent_WatchOperationServer = grpc.ServerStreamingServer[OperationEvent]

// KatlcAgent_ServiceDesc is the grpc.ServiceDesc for KatlcAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KatlcAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "katl.agent.v1.KatlcAgent",
	HandlerType: (*KatlcAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodeStatus",
			Handler:    _KatlcAgent_GetNodeStatus_Handler,
		},
		{
			MethodName: "SubmitOperation",
			Handler:    _KatlcAgent_SubmitOperation_Handler,
		},
		{
			MethodName: "CreateWorkerJoinMaterial",
			Handler:    _KatlcAgent_CreateWorkerJoinMaterial_Handler,
		},
		{
			MethodName: "GetOperation",
			Handler:    _KatlcAgent_GetOperation_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchOperation",
			Handler:       _KatlcAgent_WatchOperation_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/katlc/agentapi/agent.proto",
}
