[Output]
Format=uki
Output=katl-installer
ImageId=katl-installer

[Content]
Bootable=yes
Bootloader=systemd-boot
UnifiedKernelImages=unsigned
Packages=
        kernel-core
        kernel-modules
        systemd
        systemd-boot-unsigned
        systemd-udev
        util-linux
        coreutils
        bash
KernelCommandLine=console=ttyS0,115200n8 systemd.log_target=console loglevel=6
Hostname=katl-installer
Autologin=yes
MakeInitrd=yes

[Build]
BuildSources=../..
WorkspaceDirectory=/tmp/katl-mkosi-installer-workspace
