PasswordAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
PermitRootLogin prohibit-password
AuthorizedKeysFile /etc/ssh/authorized_keys/%u
AllowUsers root katl
HostKey /var/lib/katl/ssh/host-keys/ssh_host_ed25519_key
