[Output]
Format=sysext
Output=katl-bird
ImageId=katl-bird
Overlay=yes

[Content]
Bootable=no
BaseTrees=../../_build/mkosi/katl-runtime-root
Packages=
        bird
# The extension unit uses DynamicUser= because sysexts are merged after the
# early systemd-sysusers and systemd-tmpfiles passes.
RemoveFiles=
        /usr/lib/sysusers.d/bird.conf
        /usr/lib/tmpfiles.d/bird.conf

[Build]
BuildSources=../..
WorkspaceDirectory=/tmp/katl-mkosi-bird-workspace
