[Config]
MinimumVersion=26

[Distribution]
Distribution=fedora
Release=44
Architecture=x86-64
RepositoryKeyFetch=yes

[Output]
OutputDirectory=_build/mkosi
CompressOutput=no

[Content]
WithDocs=no
WithRecommends=no

[Build]
Incremental=yes
RepartOffline=yes
BuildSources=
WorkspaceDirectory=_build/mkosi/workspace
CacheDirectory=_build/mkosi/cache
PackageCacheDirectory=_build/mkosi/package-cache
BuildDirectory=_build/mkosi/builddir
