[Config]
MinimumVersion=26

[Distribution]
Distribution=fedora
Release=44
Architecture=x86-64
RepositoryKeyFetch=yes

[Output]
OutputDirectory=build/mkosi
CompressOutput=no

[Content]
WithDocs=no
WithRecommends=no

[Build]
Incremental=yes
RepartOffline=yes
BuildSources=
WorkspaceDirectory=build/mkosi/workspace
CacheDirectory=build/mkosi/cache
PackageCacheDirectory=build/mkosi/package-cache
BuildDirectory=build/mkosi/builddir
