[Output]
Format=sysext
Output=katl-drbd9
ImageId=katl-drbd9
Overlay=yes

[Content]
Bootable=no
BuildPackages=
        gcc
        make
        elfutils-libelf-devel
        coccinelle
        patch
        diffutils
        perl
        python3
        golang
        kmod
        tar
        gzip

[Build]
BuildSources=../..
WithNetwork=no
