[Output]
Format=sysext
Output=katl-nvidia
ImageId=katl-nvidia
Overlay=yes

[Content]
Bootable=no
BuildPackages=
        gcc
        gcc-c++
        make
        binutils
        elfutils-libelf-devel
        gawk
        hostname
        dwarves
        kmod
        tar
        gzip
        golang

[Build]
BuildSources=../..
WithNetwork=no
