// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/vmtest/proto/vmtest.proto

package vmtestpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VmtestRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TimeoutMs uint32                 `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	// Types that are valid to be assigned to Operation:
	//
	//	*VmtestRequest_Health
	//	*VmtestRequest_RunCommand
	//	*VmtestRequest_ReadFile
	//	*VmtestRequest_ExportJournal
	Operation     isVmtestRequest_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmtestRequest) Reset() {
	*x = VmtestRequest{}
	mi := &file_internal_vmtest_proto_vmtest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmtestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmtestRequest) ProtoMessage() {}

func (x *VmtestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vmtest_proto_vmtest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmtestRequest.ProtoReflect.Descriptor instead.
func (*VmtestRequest) Descriptor() ([]byte, []int) {
	return file_internal_vmtest_proto_vmtest_proto_rawDescGZIP(), []int{0}
}

func (x *VmtestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *VmtestRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *VmtestRequest) GetOperation() isVmtestRequest_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *VmtestRequest) GetHealth() *HealthRequest {
	if x != nil {
		if x, ok := x.Operation.(*VmtestRequest_Health); ok {
			return x.Health
		}
	}
	return nil
}

func (x *VmtestRequest) GetRunCommand() *RunCommandRequest {
	if x != nil {
		if x, ok := x.Operation.(*VmtestRequest_RunCommand); ok {
			return x.RunCommand
		}
	}
	return nil
}

func (x *VmtestRequest) GetReadFile() *ReadFileRequest {
	if x != nil {
		if x, ok := x.Operation.(*VmtestRequest_ReadFile); ok {
			return x.ReadFile
		}
	}
	return nil
}

func (x *VmtestRequest) GetExportJournal() *ExportJournalRequest {
	if x != nil {
		if x, ok := x.Operation.(*VmtestRequest_ExportJournal); ok {
			return x.ExportJournal
		}
	}
	return nil
}

type isVmtestRequest_Operation interface {
	isVmtestRequest_Operation()
}

type VmtestRequest_Health struct {
	Health *HealthRequest `protobuf:"bytes,10,opt,name=health,proto3,oneof"`
}

type VmtestRequest_RunCommand struct {
	RunCommand *RunCommandRequest `protobuf:"bytes,11,opt,name=run_command,json=runCommand,proto3,oneof"`
}

type VmtestRequest_ReadFile struct {
	ReadFile *ReadFileRequest `protobuf:"bytes,12,opt,name=read_file,json=readFile,proto3,oneof"`
}

type VmtestRequest_ExportJournal struct {
	ExportJournal *ExportJournalRequest `protobuf:"bytes,13,opt,name=export_journal,json=exportJournal,proto3,oneof"`
}

func (*VmtestRequest_Health) isVmtestRequest_Operation() {}

func (*VmtestRequest_RunCommand) isVmtestRequest_Operation() {}

func (*VmtestRequest_ReadFile) isVmtestRequest_Operation() {}

func (*VmtestRequest_ExportJournal) isVmtestRequest_Operation() {}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_internal_vmtest_proto_vmtest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vmtest_proto_vmtest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_internal_vmtest_proto_vmtest_proto_rawDescGZIP(), []int{1}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion  string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	BootId        string                 `protobuf:"bytes,3,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_internal_vmtest_proto_vmtest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vmtest_proto_vmtest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_vmtest_proto_vmtest_proto_rawDescGZIP(), []int{2}
}

func (x *HealthResponse) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *HealthResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HealthResponse) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

type RunCommandRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Argv             []string               `protobuf:"bytes,1,rep,name=argv,proto3" json:"argv,omitempty"`
	WorkingDirectory string                 `protobuf:"bytes,2,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	Environment      []*EnvVar              `protobuf:"bytes,3,rep,name=environment,proto3" json:"environment,omitempty"`
	StdoutLimit      uint32                 `protobuf:"varint,4,opt,name=stdout_limit,json=stdoutLimit,proto3" json:"stdout_limit,omitempty"`
	StderrLimit      uint32                 `protobuf:"varint,5,opt,name=stderr_limit,json=stderrLimit,proto3" json:"stderr_limit,omitempty"`
	SensitiveOutput  bool                   `protobuf:"varint,6,opt,name=sensitive_output,json=sensitiveOutput,proto3" json:"sensitive_output,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RunCommandRequest) Reset() {
	*x = RunCommandRequest{}
	mi := &file_internal_vmtest_proto_vmtest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandRequest) ProtoMessage() {}

func (x *RunCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vmtest_proto_vmtest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandRequest.ProtoReflect.Descriptor instead.
func (*RunCommandRequest) Descriptor() ([]byte, []int) {
	return file_internal_vmtest_proto_vmtest_proto_rawDescGZIP(), []int{3}
}

func (x *RunCommandRequest) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *RunCommandRequest) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

func (x *RunCommandRequest) GetEnvironment() []*EnvVar {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *RunCommandRequest) GetStdoutLimit() uint32 {
	if x != nil {
		return x.StdoutLimit
	}
	return 0
}

func (x *RunCommandRequest) GetStderrLimit() uint32 {
	if x != nil {
		return x.StderrLimit
	}
	return 0
}

func (x *RunCommandRequest) GetSensitiveOutput() bool {
	if x != nil {
		return x.SensitiveOutput
	}
	return false
}

type EnvVar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVar) Reset() {
	*x = EnvVar{}
	mi := &file_internal_vmtest_proto_vmtest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVar) ProtoMessage() {}

func (x *EnvVar) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vmtest_proto_vmtest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVar.ProtoReflect.Descriptor instead.
func (*EnvVar) Descriptor() ([]byte, []int) {
	return file_internal_vmtest_proto_vmtest_proto_rawDescGZIP(), []int{4}
}

func (x *EnvVar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvVar) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CommandResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExitStatus      int32                  `protobuf:"varint,1,opt,name=exit_status,json=exitStatus,proto3" json:"exit_status,omitempty"`
	Stdout          []byte                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr          []byte                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	StdoutTruncated bool                   `protobuf:"varint,4,opt,name=stdout_truncated,json=stdoutTruncated,proto3" json:"stdout_truncated,omitempty"`
	StderrTruncated bool                   `protobuf:"varint,5,opt,name=stderr_truncated,json=stderrTruncated,proto3" json:"stderr_truncated,omitempty"`
	StdoutBytes     uint32                 `protobuf:"varint,6,opt,name=stdout_bytes,json=stdoutBytes,proto3" json:"stdout_bytes,omitempty"`
	StderrBytes     uint32                 `protobuf:"varint,7,opt,name=stderr_bytes,json=stderrBytes,proto3" json:"stderr_bytes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_internal_vmtest_proto_vmtest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vmtest_proto_vmtest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_internal_vmtest_proto_vmtest_proto_rawDescGZIP(), []int{5}
}

func (x *CommandResult) GetExitStatus() int32 {
	if x != nil {
		return x.ExitStatus
	}
	return 0
}

func (x *CommandResult) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *CommandResult) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *CommandResult) GetStdoutTruncated() bool {
	if x != nil {
		return x.StdoutTruncated
	}
	return false
}

func (x *CommandResult) GetStderrTruncated() bool {
	if x != nil {
		return x.StderrTruncated
	}
	return false
}

func (x *CommandResult) GetStdoutBytes() uint32 {
	if x != nil {
		return x.StdoutBytes
	}
	return 0
}

func (x *CommandResult) GetStderrBytes() uint32 {
	if x != nil {
		return x.StderrBytes
	}
	return 0
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	MaxBytes      uint32                 `protobuf:"varint,2,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	Sensitive     bool                   `protobuf:"varint,3,opt,name=sensitive,proto3" json:"sensitive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_internal_vmtest_proto_vmtest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vmtest_proto_vmtest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_internal_vmtest_proto_vmtest_proto_rawDescGZIP(), []int{6}
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadFileRequest) GetMaxBytes() uint32 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

func (x *ReadFileRequest) GetSensitive() bool {
	if x != nil {
		return x.Sensitive
	}
	return false
}

type FileResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Truncated     bool                   `protobuf:"varint,2,opt,name=truncated,proto3" json:"truncated,omitempty"`
	SizeBytes     uint32                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Redaction     string                 `protobuf:"bytes,4,opt,name=redaction,proto3" json:"redaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileResult) Reset() {
	*x = FileResult{}
	mi := &file_internal_vmtest_proto_vmtest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResult) ProtoMessage() {}

func (x *FileResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vmtest_proto_vmtest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResult.ProtoReflect.Descriptor instead.
func (*FileResult) Descriptor() ([]byte, []int) {
	return file_internal_vmtest_proto_vmtest_proto_rawDescGZIP(), []int{7}
}

func (x *FileResult) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileResult) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *FileResult) GetSizeBytes() uint32 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileResult) GetRedaction() string {
	if x != nil {
		return x.Redaction
	}
	return ""
}

type ExportJournalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Units         []string               `protobuf:"bytes,1,rep,name=units,proto3" json:"units,omitempty"`
	BootId        string                 `protobuf:"bytes,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	MaxBytes      uint32                 `protobuf:"varint,3,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportJournalRequest) Reset() {
	*x = ExportJournalRequest{}
	mi := &file_internal_vmtest_proto_vmtest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportJournalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportJournalRequest) ProtoMessage() {}

func (x *ExportJournalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vmtest_proto_vmtest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportJournalRequest.ProtoReflect.Descriptor instead.
func (*ExportJournalRequest) Descriptor() ([]byte, []int) {
	return file_internal_vmtest_proto_vmtest_proto_rawDescGZIP(), []int{8}
}

func (x *ExportJournalRequest) GetUnits() []string {
	if x != nil {
		return x.Units
	}
	return nil
}

func (x *ExportJournalRequest) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *ExportJournalRequest) GetMaxBytes() uint32 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

type JournalResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Truncated     bool                   `protobuf:"varint,2,opt,name=truncated,proto3" json:"truncated,omitempty"`
	SizeBytes     uint32                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JournalResult) Reset() {
	*x = JournalResult{}
	mi := &file_internal_vmtest_proto_vmtest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JournalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalResult) ProtoMessage() {}

func (x *JournalResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vmtest_proto_vmtest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalResult.ProtoReflect.Descriptor instead.
func (*JournalResult) Descriptor() ([]byte, []int) {
	return file_internal_vmtest_proto_vmtest_proto_rawDescGZIP(), []int{9}
}

func (x *JournalResult) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *JournalResult) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *JournalResult) GetSizeBytes() uint32 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type VmtestError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Details       map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmtestError) Reset() {
	*x = VmtestError{}
	mi := &file_internal_vmtest_proto_vmtest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmtestError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmtestError) ProtoMessage() {}

func (x *VmtestError) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vmtest_proto_vmtest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmtestError.ProtoReflect.Descriptor instead.
func (*VmtestError) Descriptor() ([]byte, []int) {
	return file_internal_vmtest_proto_vmtest_proto_rawDescGZIP(), []int{10}
}

func (x *VmtestError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *VmtestError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VmtestError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *VmtestError) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type VmtestResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RequestId  string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DurationMs uint64                 `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*VmtestResponse_Health
	//	*VmtestResponse_Command
	//	*VmtestResponse_File
	//	*VmtestResponse_Journal
	//	*VmtestResponse_Error
	Result        isVmtestResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmtestResponse) Reset() {
	*x = VmtestResponse{}
	mi := &file_internal_vmtest_proto_vmtest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmtestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmtestResponse) ProtoMessage() {}

func (x *VmtestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vmtest_proto_vmtest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmtestResponse.ProtoReflect.Descriptor instead.
func (*VmtestResponse) Descriptor() ([]byte, []int) {
	return file_internal_vmtest_proto_vmtest_proto_rawDescGZIP(), []int{11}
}

func (x *VmtestResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *VmtestResponse) GetDurationMs() uint64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *VmtestResponse) GetResult() isVmtestResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *VmtestResponse) GetHealth() *HealthResponse {
	if x != nil {
		if x, ok := x.Result.(*VmtestResponse_Health); ok {
			return x.Health
		}
	}
	return nil
}

func (x *VmtestResponse) GetCommand() *CommandResult {
	if x != nil {
		if x, ok := x.Result.(*VmtestResponse_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *VmtestResponse) GetFile() *FileResult {
	if x != nil {
		if x, ok := x.Result.(*VmtestResponse_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *VmtestResponse) GetJournal() *JournalResult {
	if x != nil {
		if x, ok := x.Result.(*VmtestResponse_Journal); ok {
			return x.Journal
		}
	}
	return nil
}

func (x *VmtestResponse) GetError() *VmtestError {
	if x != nil {
		if x, ok := x.Result.(*VmtestResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isVmtestResponse_Result interface {
	isVmtestResponse_Result()
}

type VmtestResponse_Health struct {
	Health *HealthResponse `protobuf:"bytes,10,opt,name=health,proto3,oneof"`
}

type VmtestResponse_Command struct {
	Command *CommandResult `protobuf:"bytes,11,opt,name=command,proto3,oneof"`
}

type VmtestResponse_File struct {
	File *FileResult `protobuf:"bytes,12,opt,name=file,proto3,oneof"`
}

type VmtestResponse_Journal struct {
	Journal *JournalResult `protobuf:"bytes,13,opt,name=journal,proto3,oneof"`
}

type VmtestResponse_Error struct {
	Error *VmtestError `protobuf:"bytes,100,opt,name=error,proto3,oneof"`
}

func (*VmtestResponse_Health) isVmtestResponse_Result() {}

func (*VmtestResponse_Command) isVmtestResponse_Result() {}

func (*VmtestResponse_File) isVmtestResponse_Result() {}

func (*VmtestResponse_Journal) isVmtestResponse_Result() {}

func (*VmtestResponse_Error) isVmtestResponse_Result() {}

var File_internal_vmtest_proto_vmtest_proto protoreflect.FileDescriptor

const file_internal_vmtest_proto_vmtest_proto_rawDesc = "" +
	"\n" +
	"\"internal/vmtest/proto/vmtest.proto\x12\x0ekatl.vmtest.v1\"\xe8\x02\n" +
	"\rVmtestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\rR\ttimeoutMs\x127\n" +
	"\x06health\x18\n" +
	" \x01(\v2\x1d.katl.vmtest.v1.HealthRequestH\x00R\x06health\x12D\n" +
	"\vrun_command\x18\v \x01(\v2!.katl.vmtest.v1.RunCommandRequestH\x00R\n" +
	"runCommand\x12>\n" +
	"\tread_file\x18\f \x01(\v2\x1f.katl.vmtest.v1.ReadFileRequestH\x00R\breadFile\x12M\n" +
	"\x0eexport_journal\x18\r \x01(\v2$.katl.vmtest.v1.ExportJournalRequestH\x00R\rexportJournalB\v\n" +
	"\toperation\"\x0f\n" +
	"\rHealthRequest\"j\n" +
	"\x0eHealthResponse\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x17\n" +
	"\aboot_id\x18\x03 \x01(\tR\x06bootId\"\xff\x01\n" +
	"\x11RunCommandRequest\x12\x12\n" +
	"\x04argv\x18\x01 \x03(\tR\x04argv\x12+\n" +
	"\x11working_directory\x18\x02 \x01(\tR\x10workingDirectory\x128\n" +
	"\venvironment\x18\x03 \x03(\v2\x16.katl.vmtest.v1.EnvVarR\venvironment\x12!\n" +
	"\fstdout_limit\x18\x04 \x01(\rR\vstdoutLimit\x12!\n" +
	"\fstderr_limit\x18\x05 \x01(\rR\vstderrLimit\x12)\n" +
	"\x10sensitive_output\x18\x06 \x01(\bR\x0fsensitiveOutput\"2\n" +
	"\x06EnvVar\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xfc\x01\n" +
	"\rCommandResult\x12\x1f\n" +
	"\vexit_status\x18\x01 \x01(\x05R\n" +
	"exitStatus\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\fR\x06stderr\x12)\n" +
	"\x10stdout_truncated\x18\x04 \x01(\bR\x0fstdoutTruncated\x12)\n" +
	"\x10stderr_truncated\x18\x05 \x01(\bR\x0fstderrTruncated\x12!\n" +
	"\fstdout_bytes\x18\x06 \x01(\rR\vstdoutBytes\x12!\n" +
	"\fstderr_bytes\x18\a \x01(\rR\vstderrBytes\"`\n" +
	"\x0fReadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1b\n" +
	"\tmax_bytes\x18\x02 \x01(\rR\bmaxBytes\x12\x1c\n" +
	"\tsensitive\x18\x03 \x01(\bR\tsensitive\"\x81\x01\n" +
	"\n" +
	"FileResult\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x1c\n" +
	"\ttruncated\x18\x02 \x01(\bR\ttruncated\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\rR\tsizeBytes\x12\x1c\n" +
	"\tredaction\x18\x04 \x01(\tR\tredaction\"b\n" +
	"\x14ExportJournalRequest\x12\x14\n" +
	"\x05units\x18\x01 \x03(\tR\x05units\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\tR\x06bootId\x12\x1b\n" +
	"\tmax_bytes\x18\x03 \x01(\rR\bmaxBytes\"`\n" +
	"\rJournalResult\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1c\n" +
	"\ttruncated\x18\x02 \x01(\bR\ttruncated\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\rR\tsizeBytes\"\xd9\x01\n" +
	"\vVmtestError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x12B\n" +
	"\adetails\x18\x04 \x03(\v2(.katl.vmtest.v1.VmtestError.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf1\x02\n" +
	"\x0eVmtestResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vduration_ms\x18\x02 \x01(\x04R\n" +
	"durationMs\x128\n" +
	"\x06health\x18\n" +
	" \x01(\v2\x1e.katl.vmtest.v1.HealthResponseH\x00R\x06health\x129\n" +
	"\acommand\x18\v \x01(\v2\x1d.katl.vmtest.v1.CommandResultH\x00R\acommand\x120\n" +
	"\x04file\x18\f \x01(\v2\x1a.katl.vmtest.v1.FileResultH\x00R\x04file\x129\n" +
	"\ajournal\x18\r \x01(\v2\x1d.katl.vmtest.v1.JournalResultH\x00R\ajournal\x123\n" +
	"\x05error\x18d \x01(\v2\x1b.katl.vmtest.v1.VmtestErrorH\x00R\x05errorB\b\n" +
	"\x06resultB7Z5github.com/zariel/katl/internal/vmtest/proto;vmtestpbb\x06proto3"

var (
	file_internal_vmtest_proto_vmtest_proto_rawDescOnce sync.Once
	file_internal_vmtest_proto_vmtest_proto_rawDescData []byte
)

func file_internal_vmtest_proto_vmtest_proto_rawDescGZIP() []byte {
	file_internal_vmtest_proto_vmtest_proto_rawDescOnce.Do(func() {
		file_internal_vmtest_proto_vmtest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_vmtest_proto_vmtest_proto_rawDesc), len(file_internal_vmtest_proto_vmtest_proto_rawDesc)))
	})
	return file_internal_vmtest_proto_vmtest_proto_rawDescData
}

var file_internal_vmtest_proto_vmtest_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_vmtest_proto_vmtest_proto_goTypes = []any{
	(*VmtestRequest)(nil),        // 0: katl.vmtest.v1.VmtestRequest
	(*HealthRequest)(nil),        // 1: katl.vmtest.v1.HealthRequest
	(*HealthResponse)(nil),       // 2: katl.vmtest.v1.HealthResponse
	(*RunCommandRequest)(nil),    // 3: katl.vmtest.v1.RunCommandRequest
	(*EnvVar)(nil),               // 4: katl.vmtest.v1.EnvVar
	(*CommandResult)(nil),        // 5: katl.vmtest.v1.CommandResult
	(*ReadFileRequest)(nil),      // 6: katl.vmtest.v1.ReadFileRequest
	(*FileResult)(nil),           // 7: katl.vmtest.v1.FileResult
	(*ExportJournalRequest)(nil), // 8: katl.vmtest.v1.ExportJournalRequest
	(*JournalResult)(nil),        // 9: katl.vmtest.v1.JournalResult
	(*VmtestError)(nil),          // 10: katl.vmtest.v1.VmtestError
	(*VmtestResponse)(nil),       // 11: katl.vmtest.v1.VmtestResponse
	nil,                          // 12: katl.vmtest.v1.VmtestError.DetailsEntry
}
var file_internal_vmtest_proto_vmtest_proto_depIdxs = []int32{
	1,  // 0: katl.vmtest.v1.VmtestRequest.health:type_name -> katl.vmtest.v1.HealthRequest
	3,  // 1: katl.vmtest.v1.VmtestRequest.run_command:type_name -> katl.vmtest.v1.RunCommandRequest
	6,  // 2: katl.vmtest.v1.VmtestRequest.read_file:type_name -> katl.vmtest.v1.ReadFileRequest
	8,  // 3: katl.vmtest.v1.VmtestRequest.export_journal:type_name -> katl.vmtest.v1.ExportJournalRequest
	4,  // 4: katl.vmtest.v1.RunCommandRequest.environment:type_name -> katl.vmtest.v1.EnvVar
	12, // 5: katl.vmtest.v1.VmtestError.details:type_name -> katl.vmtest.v1.VmtestError.DetailsEntry
	2,  // 6: katl.vmtest.v1.VmtestResponse.health:type_name -> katl.vmtest.v1.HealthResponse
	5,  // 7: katl.vmtest.v1.VmtestResponse.command:type_name -> katl.vmtest.v1.CommandResult
	7,  // 8: katl.vmtest.v1.VmtestResponse.file:type_name -> katl.vmtest.v1.FileResult
	9,  // 9: katl.vmtest.v1.VmtestResponse.journal:type_name -> katl.vmtest.v1.JournalResult
	10, // 10: katl.vmtest.v1.VmtestResponse.error:type_name -> katl.vmtest.v1.VmtestError
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_internal_vmtest_proto_vmtest_proto_init() }
func file_internal_vmtest_proto_vmtest_proto_init() {
	if File_internal_vmtest_proto_vmtest_proto != nil {
		return
	}
	file_internal_vmtest_proto_vmtest_proto_msgTypes[0].OneofWrappers = []any{
		(*VmtestRequest_Health)(nil),
		(*VmtestRequest_RunCommand)(nil),
		(*VmtestRequest_ReadFile)(nil),
		(*VmtestRequest_ExportJournal)(nil),
	}
	file_internal_vmtest_proto_vmtest_proto_msgTypes[11].OneofWrappers = []any{
		(*VmtestResponse_Health)(nil),
		(*VmtestResponse_Command)(nil),
		(*VmtestResponse_File)(nil),
		(*VmtestResponse_Journal)(nil),
		(*VmtestResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_vmtest_proto_vmtest_proto_rawDesc), len(file_internal_vmtest_proto_vmtest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_vmtest_proto_vmtest_proto_goTypes,
		DependencyIndexes: file_internal_vmtest_proto_vmtest_proto_depIdxs,
		MessageInfos:      file_internal_vmtest_proto_vmtest_proto_msgTypes,
	}.Build()
	File_internal_vmtest_proto_vmtest_proto = out.File
	file_internal_vmtest_proto_vmtest_proto_goTypes = nil
	file_internal_vmtest_proto_vmtest_proto_depIdxs = nil
}
